[pocketbase]
url = "http://localhost:8090"
admin_email = "admin@syncapp.local"
admin_password = "supersecret123"
timeout_secs = 30
retry_attempts = 3
retry_delay_secs = 5

[daemon]
pid_file = "sync-daemon.pid"
log_file = "sync-daemon.log"
log_level = "info"
config_refresh_interval_secs = 60
auto_restart_on_config_change = false

[telemetry]
log_level = "info"
json_logging = false
console_logging = true

[telemetry.metrics]
enabled = true
bind_address = "127.0.0.1"
port = 9091

[concurrency]
max_concurrent_syncs = 2
max_file_operations = 50
sync_queue_size = 100

[cache]
cache_dir = ".cache"
config_cache_ttl_secs = 300
file_metadata_cache_ttl_secs = 60
enable_persistent_cache = true
