name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'book.toml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'book.toml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Setup mdBook plugins
      run: |
        cargo install mdbook-linkcheck
        cargo install mdbook-toc
        cargo install mdbook-mermaid

    - name: Build documentation
      run: |
        mdbook build
        
        # Add CNAME file for custom domain if needed
        # echo 'docs.sync-app.com' > docs-site/CNAME

    - name: Validate links
      run: mdbook test

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs-site

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

  link-checker:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Install link checker
      run: cargo install mdbook-linkcheck

    - name: Check links
      run: |
        mdbook build
        mdbook test

    - name: Comment on PR
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Documentation build failed. Please check the logs for broken links or formatting issues.'
          })

  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Build preview
      run: mdbook build

    - name: Deploy to preview environment
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'pull_request'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site
        destination_dir: pr-${{ github.event.number }}
        
    - name: Comment preview link
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.issue.number;
          const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-${prNumber}/`;
          
          github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `📚 Documentation preview available at: ${previewUrl}`
          })
